### ISSUE TITLE
How do i make routes for the authenticated users?

### ISSUE THREAD

**Issue by SharksT** [ocboogie/authful-actix-web#3]
I'm new to rust, that why I have that kind of question, I only now that I have to use LoggedClient but don't know-how.

**Comment by ocboogie** [comment]
The [`logout`](https://github.com/ocboogie/authful-actix-web/blob/master/http_transport/src/routes/auth.rs#L57) route has this functionality so you can use it for reference. You basically add `LoggedUser` as a argument to the route and everything should be handled. If a user isn't authenticated the server will throw an error automatically. If a user is authenticated then the `LoggedUser` argument should contain the user id and the session id.

A lot of this project is based on [this blog post](https://gill.net.in/posts/auth-microservice-rust-actix-web1.0-diesel-complete-tutorial/). I think going through this and following along step by step on your own project would be a great way to learn. My project does have some key differences but it shouldn't really matter. The post even has a part on how to implement `LoggedUser`, so that might give you a better understanding.

**Comment by ocboogie** [comment]
I would like to say, if you're new to Rust and trying to learn it, this project might be a bit much. From what I've seen, Diesel, the ORM used in this project, is one of the most complex Rust libraries. This combined with the async stuff makes this project more complicated and harder to read than the average Rust project. When I was learning Rust, I had a lot of fun playing around with [ggez](https://github.com/ggez/ggez). But hey, if you're having fun and learning from it, go ahead.

**Comment by SharksT** [comment]
I'm actually using this because I fall in love with rust and talked about at work, so my boss allowed me to do an API to the mobile app that my team is currently working on. I'm using your authentication service combined with some Redis, juniper and sonic_server.
Your project and you helped me a lot to learn some important things, thank you!

**Comment by ocboogie** [comment]
Wow, that's awesome. I, too, have fallen in love with Rust and want to use it just about everywhere. Although, I do want to say that this code is not pen tested. I've tried to follow all the modern security advice (e.g. using Argon2 for password hashing, keeping session state on the server for easy revoking, etc), but I am no security expert. Use this code at your own discretion. :)
